JShop/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :followships
  resources :shops
  resources :deliveries

  resources :s_orders do
    post :is_shipped, on: :member
    post :is_delivered, on: :member
  end

  resources :orders do
    post :is_completed, on: :member
    post :is_cancelled, on: :member
  end

  resources :favorites

  resources :carts do
    post :inc_one, on: :member
    post :dec_one, on: :member
  end

  resources :products

  devise_for :users
  
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

JShop/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

JShop/app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

JShop/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user
  belongs_to :s_order
end

JShop/app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :s_order
end

JShop/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

JShop/app/models/followship.rb
class Followship < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

JShop/app/models/order.rb
class Order < ApplicationRecord
    has_many :s_orders, dependent: :destroy

    scope :filter_by_status, -> (status) { where status: status }
end

JShop/app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image_dir
    validates :name, :price, :description, :image_dir,  presence: true
    belongs_to :user

    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :carts, dependent: :destroy
    has_many :s_orders, dependent: :destroy
end

JShop/app/models/s_order.rb
class SOrder < ApplicationRecord
  belongs_to :order
  belongs_to :product
  has_one :delivery, dependent: :destroy
  has_one :comment, dependent: :destroy

  scope :filter_by_status, -> (status) { where status: status }
end

JShop/app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
end

JShop/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:login]

  has_many :carts, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one :shop, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :followships, dependent: :destroy

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  attr_writer :login

  validate :validate_username

  def login
    @login || self.username || self.email
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
end

JShop/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]
  before_action :check_for_same?, only: %i[ new create ]

  # GET /carts or /carts.json
  def index
    if user_signed_in?
      if current_user.role == 1
        @owned_carts = Cart.where(user_id: current_user.id)

        @total_price = 0

        @owned_carts.each do |owned_cart|
          @temp_product = Product.find_by(id: owned_cart.product_id)
          @total_price += @temp_product.price.to_d * owned_cart.quantity.to_i
        end
      end
    end
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # quantity += 1
  def inc_one
    @cart = Cart.find(params[:id])
    @cart.update(quantity: @cart.quantity + 1)

    redirect_back(fallback_location: @cart)
  end

  # quantity -= 1
  def dec_one
    @cart = Cart.find(params[:id])
    @cart.update(quantity: @cart.quantity - 1)

    if @cart.quantity == 0
      @cart.destroy
    end

    redirect_back(fallback_location: @cart)
  end

  # POST /carts or /carts.json
  def create
    if @updated
      return
    end

    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        return
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def check_for_same?
    if Cart.find_by(user_id: params[:user_id], product_id: params[:product_id])
      @old_cart = Cart.find_by(user_id: params[:user_id], product_id: params[:product_id])
      @update_quantity = @old_cart.quantity + params[:quantity].to_i
      @old_cart.update(:quantity => @update_quantity)
      @updated = true
      return
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.permit(:user_id, :product_id, :quantity)
    end
end

JShop/app/helpers/application_helper.rb
module ApplicationHelper
end

JShop/app/helpers/carts_helper.rb
module CartsHelper
end

JShop/app/helpers/comments_helper.rb
module CommentsHelper
end

JShop/app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

JShop/app/helpers/favorites_helper.rb
module FavoritesHelper
end

JShop/app/helpers/followships_helper.rb
module FollowshipsHelper
end

JShop/app/helpers/home_helper.rb
module HomeHelper
end

JShop/app/helpers/orders_helper.rb
module OrdersHelper
end

JShop/app/helpers/products_helper.rb
module ProductsHelper
end

JShop/app/helpers/s_orders_helper.rb
module SOrdersHelper
end

JShop/app/helpers/shops_helper.rb
module ShopsHelper
end

JShop/app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

JShop/app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

JShop/app/views/carts/index.html.erb
<h2 class="ms-5 mt-5 mb-4">购物车</h2>

<div class="mx-5 mb-5 d-flex" style="min-width: 700px">
  <div class="d-flex flex-column justify-content-center mb-4"
    style="background-color: #F5F5F5; border-radius: 20px; width: 78%; margin-right: 2%;">
    <div class="m-4 mb-0 d-flex flex-column">
      <div class="d-flex flex-column mx-3 mt-3">
        <% if !@owned_carts.empty?%>
          <% @owned_carts.each do |owned_cart| %>
            <div class="d-flex" style="border-radius: 20px; margin-bottom: 40px;">
              <% @cart_product = Product.find_by(id: owned_cart.product_id) %>
              
              <div>
                <%= link_to @cart_product do %>
                  <% if @cart_product.image_dir.attached? %>
                    <img src="<%= (url_for(@cart_product.image_dir)) %>" style="height: 15rem; width: 15rem; border-radius: 15px; border: 1px solid black;">
                  <% end %>
                <% end %>
              </div>

              <div class="d-flex flex-column mx-4 my-1">
                <div class="ms-1">
                  <%= link_to @cart_product, :style => "color: black; text-decoration: none;" do %>
                    <h4><%= @cart_product.name %></h4>
                  <% end %>
                </div>

                <div class="mt-1 mb-1 ms-1">
                  <%= link_to @fav_product, :style => "color: black; text-decoration: none;" do %>
                    <span style="font-size: 18px;"><%= @cart_product.description %></span>
                  <% end %>
                </div>

                <div class="mt-1 ms-1">
                  <%= link_to @cart_product, :style => "color: black; text-decoration: none;" do %>
                    <span style="font-size: 18px;">x<%= owned_cart.quantity %></span>
                  <% end %>
                </div>

                <div class="mt-2 ms-1">
                  <%= link_to @cart_product, :style => "color: black; text-decoration: none;" do %>
                    <div class="d-flex">
                      <h5 style="font-size: 17px; margin-top: 4px; margin-right: 5px;"> 单价：</h5>
                      <span style="font-size: 18px;">¥ <%= (@cart_product.price).to_f %></span>
                    </div>
                  <% end %>
                </div>

                <div class="mt-1 ms-1 mb-1">
                  <%= link_to @cart_product, :style => "color: black; text-decoration: none;" do %>
                    <div class="d-flex">
                      <h5 style="font-size: 17px; margin-top: 4px; margin-right: 5px;"> 总额：</h5>
                      <span style="font-size: 18px;">¥ <%= (@cart_product.price * owned_cart.quantity).to_f %></span>
                    </div>
                  <% end %>
                </div>

                <div class="d-flex">
                  <div class="mt-2 me-2">
                    <%= link_to inc_one_cart_path(id: owned_cart.id), method: :post do %>
                      <button class="btn" style="background-color: grey; height: 40px; width: 43px;">
                        <div>
                          <h5 style="color: white;"> + </h5>
                        </div>
                      </button>
                    <% end %>
                  </div>

                  <div class="mt-2 me-2">
                    <%= link_to dec_one_cart_path(id: owned_cart.id), method: :post do %>
                      <button class="btn" style="background-color: grey; height: 40px; width: 43px;">
                        <div>
                          <h5 style="color: white;"> - </h5>
                        </div>
                      </button>
                    <% end %>
                  </div>

                  <div class="mt-2">
                    <%= link_to owned_cart, method: :delete do %>
                      <button class="btn" style="background-color:darkred; height: 40px; width: 43px;">
                        <div>
                          <%= image_tag 'bin.png', style: 'height:18px; width:18px;' %>
                        </div>
                      </button>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <div class="ms-5 mb-5">
            <span style="color: grey; font-size: 17px;"> 您还未有订单。</span>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="d-flex flex-column mb-4"
    style="background-color: #F5F5F5; border-radius: 20px; width: 20%; min-width: 200px;">
    <div class="mx-2 my-2 d-flex flex-column">
      <h4 class="ms-4 mt-4 mb-3">付款金额</h4>
      <span class="ms-4" style="font-size: 25px;"> ¥ <%= @total_price %> </span>

      <div class="ms-4 mt-3 mb-4">
        <!-- make all products in carts into one main order -->
        <% if @owned_carts.size > 0 %>
          <%= link_to orders_path(:user_id => current_user.id, :deal_sum => @total_price.to_f,
              :delivery_address => current_user.address, :delivery_name => current_user.username,
              :delivery_phone => current_user.phone_number, :order_status => "Paid"), method: :post do %>
            <button class="btn btn-primary" style="width: 100px;" type="submit"> 
              付款 
            </button>
          <% end %>
        <% else %>
          <button class="btn btn-secondary disabled" style="width: 100px; cursor: default;"> 付款 </button>
        <% end %>
      </div>
    </div>
  </div>
</div>

JShop/app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

JShop/app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @cart.user_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @cart.product_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @cart.quantity %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>