JShop/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :followships
  resources :shops
  resources :deliveries

  resources :s_orders do
    post :is_shipped, on: :member
    post :is_delivered, on: :member
  end

  resources :orders do
    post :is_completed, on: :member
    post :is_cancelled, on: :member
  end

  resources :favorites

  resources :carts do
    post :inc_one, on: :member
    post :dec_one, on: :member
  end

  resources :products

  devise_for :users
  
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

JShop/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

JShop/app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

JShop/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user
  belongs_to :s_order
end

JShop/app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :s_order
end

JShop/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

JShop/app/models/followship.rb
class Followship < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

JShop/app/models/order.rb
class Order < ApplicationRecord
    has_many :s_orders, dependent: :destroy

    scope :filter_by_status, -> (status) { where status: status }
end

JShop/app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image_dir
    validates :name, :price, :description, :image_dir,  presence: true
    belongs_to :user

    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :carts, dependent: :destroy
    has_many :s_orders, dependent: :destroy
end

JShop/app/models/s_order.rb
class SOrder < ApplicationRecord
  belongs_to :order
  belongs_to :product
  has_one :delivery, dependent: :destroy
  has_one :comment, dependent: :destroy

  scope :filter_by_status, -> (status) { where status: status }
end

JShop/app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
end

JShop/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:login]

  has_many :carts, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one :shop, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :followships, dependent: :destroy

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  attr_writer :login

  validate :validate_username

  def login
    @login || self.username || self.email
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
end

JShop/app/helpers/carts_helper.rb
module CartsHelper
end

JShop/app/helpers/comments_helper.rb
module CommentsHelper
end

JShop/app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

JShop/app/helpers/favorites_helper.rb
module FavoritesHelper
end

JShop/app/helpers/home_helper.rb
module HomeHelper
end

JShop/app/helpers/orders_helper.rb
module OrdersHelper
end

JShop/app/helpers/products_helper.rb
module ProductsHelper
end

JShop/app/helpers/s_orders_helper.rb
module SOrdersHelper
end

JShop/app/helpers/shops_helper.rb
module ShopsHelper
end

JShop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-white d-flex justify-content-end mt-2" style="min-width: 800px;">
      <div class="float-right d-flex flex-row-reverse">
        <!-- login buttons -->
        <% if user_signed_in? %>
          <div style="margin-left: 20px; margin-right: 20px; text-decoration: none !important;">
            <%= link_to destroy_user_session_path, method: :delete do %>
              <button class="btn btn-outline-dark" type="submit">登出</button>
            <% end %>
          </div>

          <div>
            <%= link_to edit_user_registration_path, method: :get do %>
              <button class="btn btn-primary" type="submit"> <%= current_user.username %> </button>
            <% end %>
          </div>
        <% else %>
          <div style="margin-right: 20px; text-decoration: none !important;">
            <%= link_to new_user_session_path, method: :get do %>
                <button class="btn btn-outline-dark" type="submit">登录</button>
            <% end %>
          </div>

          <div style="margin-right: 20px; text-decoration: none !important;">
            <%= link_to new_user_registration_path, method: :get do %>
                <button class="btn btn-secondary" type="submit">注册</button>
            <% end %>
          </div>
        <% end %>
      </div>
    </nav>

    <nav class="navbar navbar-light bg-white" style="min-width: 800px; border-bottom: 1px solid grey">
      <a class="navbar-brand" href="/">
        <%= image_tag 'logo.png', style: 'height:40px; width:80px; margin-left: 20px;' %>
      </a>

      <% if user_signed_in? %>
        <% if current_user.role == 1 %>
          <div>
            <form class="form-inline d-flex align-items-center">
              <input class="form-control" style="height: 40px;" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 mx-3 ml-3" type="submit">Search</button>
            </form>
          </div>
        <% elsif current_user.role == 2 %>
          <% @owned_shop = Shop.find_by(user_id: current_user.id) %>

          <div>
            <%= link_to @owned_shop, style: "color: grey; text-decoration: underline;", method: :get do %>
              <span> 点此查看您的商店页面 </span>
            <% end %>
          </div>
        <% elsif current_user.role == 4 %>

        <% end %>
      <% else %>
        <div>
          <form class="form-inline d-flex align-items-center">
            <input class="form-control" style="height: 40px;" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 mx-3 ml-3" type="submit">Search</button>
          </form>
        </div>
      <% end %>


      <div>
        <% if user_signed_in? %>
          <% if current_user.role == 1 %>
            <!-- fav, cart -->
            <div class="d-flex">
              <div class="d-flex align-items-center">
                <!-- link to fav page later-->
                <%= link_to favorites_path, method: :get do %>
                  <div>
                    <%= image_tag 'heart.png', style: 'height:25px; width:25px;' %>
                  </div>
                <% end %>
              </div>

              <div style="margin-right: 25px; margin-left: 25px;">
                <!-- link to cart page later-->
                <%= link_to carts_path, method: :get do %>
                  <div>
                    <%= image_tag 'cart.png', style: 'height:25px; width:25px;' %>
                  </div>
                <% end %>
              </div>
            </div>
          <% elsif current_user.role == 2 %>
            <!-- addItem, orders -->
            <div class="d-flex">
              <div class="d-flex align-items-center">
                <!-- link to add item page later-->
                <%= link_to new_product_path, method: :get do %>
                  <div>
                    <%= image_tag 'plus.png', style: 'height:20px; width:20px;' %>
                  </div>
                <% end %>
              </div>

              <div style="margin-right: 25px; margin-left: 25px;">
                <!-- link to order list page later-->
                <%= link_to s_orders_path, method: :get do %>
                  <div>
                    <%= image_tag 'order.png', style: 'height:25px; width:25px;' %>
                  </div>
                <% end %>
              </div>
            </div>
          <% elsif current_user.role == 3 %>
            <!-- notifications -->

          <% elsif current_user.role == 4 %>
            <div class="d-flex">

            </div>
          <% end %>
        <% else %>
          <!-- fav, cart, but login required -->
          <div class="d-flex">
            <div class="d-flex align-items-center">
              <%= link_to new_user_session_path, method: :get do %>
                <div>
                  <%= image_tag 'heart.png', style: 'height:25px; width:25px;' %>
                </div>
              <% end %>
            </div>

            <div style="margin-right: 25px; margin-left: 25px;">
              <%= link_to new_user_session_path, method: :get do %>
                <div>
                  <%= image_tag 'cart.png', style: 'height:25px; width:25px;' %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </nav>
    

    <%# <p class="notice"><%= notice</p> %>
    
    <%= yield %>

    <nav class="navbar navbar-light bg-white d-flex justify-content-center" style="height: 80px; min-width: 800px; border-top: 1px solid grey">
      <p style="color:grey">JShop by 79066013 陈嘉骏</p>
    </nav>
  </body>
</html>