JShop/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :followships
  resources :shops
  resources :deliveries

  resources :s_orders do
    post :is_shipped, on: :member
    post :is_delivered, on: :member
  end

  resources :orders do
    post :is_completed, on: :member
    post :is_cancelled, on: :member
  end

  resources :favorites

  resources :carts do
    post :inc_one, on: :member
    post :dec_one, on: :member
  end

  resources :products

  devise_for :users
  
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

JShop/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

JShop/app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

JShop/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user
  belongs_to :s_order
end

JShop/app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :s_order
end

JShop/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

JShop/app/models/followship.rb
class Followship < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

JShop/app/models/order.rb
class Order < ApplicationRecord
    has_many :s_orders, dependent: :destroy

    scope :filter_by_status, -> (status) { where status: status }
end

JShop/app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image_dir
    validates :name, :price, :description, :image_dir,  presence: true
    belongs_to :user

    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :carts, dependent: :destroy
    has_many :s_orders, dependent: :destroy
end

JShop/app/models/s_order.rb
class SOrder < ApplicationRecord
  belongs_to :order
  belongs_to :product
  has_one :delivery, dependent: :destroy
  has_one :comment, dependent: :destroy

  scope :filter_by_status, -> (status) { where status: status }
end

JShop/app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
end

JShop/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:login]

  has_many :carts, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one :shop, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :followships, dependent: :destroy

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  attr_writer :login

  validate :validate_username

  def login
    @login || self.username || self.email
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
end

JShop/app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[ show edit update destroy ]
  before_action :check_buyer, only: %i[ index edit destroy update ]

  # GET /shops or /shops.json
  def index
    @shops = Shop.all
    @shop_products = Product.where(user_id: @shop.user_id)
    @ranked_products = (@shop_products.all.sort_by &:sales).first(10)
    
  end

  # GET /shops/1 or /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops or /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: "Shop was successfully created." }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1 or /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: "Shop was successfully updated." }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1 or /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: "Shop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def check_buyer
    if user_signed_in?
      if current_user.role != 3
        redirect_to root_path
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:user_id)
    end
end

JShop/app/helpers/application_helper.rb
module ApplicationHelper
end

JShop/app/helpers/carts_helper.rb
module CartsHelper
end

JShop/app/helpers/comments_helper.rb
module CommentsHelper
end

JShop/app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

JShop/app/helpers/favorites_helper.rb
module FavoritesHelper
end

JShop/app/helpers/followships_helper.rb
module FollowshipsHelper
end

JShop/app/helpers/home_helper.rb
module HomeHelper
end

JShop/app/helpers/orders_helper.rb
module OrdersHelper
end

JShop/app/helpers/products_helper.rb
module ProductsHelper
end

JShop/app/helpers/s_orders_helper.rb
module SOrdersHelper
end

JShop/app/helpers/shops_helper.rb
module ShopsHelper
end

JShop/app/views/shops/_form.html.erb
<%= form_with(model: shop) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
        <% shop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

JShop/app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

JShop/app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shops</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.user_id %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path %>

JShop/app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', shops_path %>

JShop/app/views/shops/show.html.erb
<div class="d-flex m-5" style="min-width: 700px;">
  <div class="d-flex flex-column" style="width: 20%; min-width: 250px; height: auto;">
    <div class="d-flex flex-column" style="border-radius: 20px; background-color: #F5F5F5;">
      <% @shop_owner = User.find_by(id: @shop.user_id) %>
      <div class="d-flex justify-content-center mt-4">
        <h4> <%= @shop_owner.username %> </h4>
      </div>

      <div class="d-flex justify-content-center mb-2">
        <span style="font-size: 14px; color: grey;"> <%= @shop_owner.created_at %> </span>
      </div>

      <div class="d-flex justify-content-center">
        <div class="d-flex mt-2 mb-1">
          <h5 class="mt-1 me-3" style="font-size: 15px;"> 商品数: </h5>
          <!-- get followship counts -->
          <% @product_count = Product.where(user_id: @shop.user_id).count %>
          <span style="font-size: 16px; margin-top: 1px;"> <%= @product_count %> </span>
        </div>
      </div>

      <div class="d-flex justify-content-center">
        <div class="d-flex mb-1">
          <h5 class="mt-1 me-3" style="font-size: 15px;"> 关注人数: </h5>
          <!-- get followship counts -->
          <% @following_count = Followship.where(shop_id: @shop.id).count %>
          <span style="font-size: 16px; margin-top: 1px;"> <%= @following_count %> </span>
        </div>
      </div>

      <div class="d-flex justify-content-center">
        <div class="d-flex mb-3">
          <h5 class="mt-1 me-3" style="font-size: 15px;"> 评价: </h5>
          <!-- get avg rating -->
          <% @comments = Comment.where(seller_id: @shop.user_id) %>
          <% @average_rating = @comments.sum("rating").to_f / @comments.count.to_f %>
          <span style="font-size: 16px; margin-top: 1px;"> <%= @average_rating %> 星</span>
        </div>
      </div>

      <div class="d-flex mt-1 align-items-center justify-content-center" style="margin-bottom: 35px;">
        <div class="d-flex me-3">
          <% if user_signed_in? %>
            <% if current_user.role == 1 %>
              <% @get_followship = Followship.where(user_id: current_user.id, shop_id: @shop.id).any? %>

              <% if !@get_followship %>
                <%= link_to followships_path(:user_id => current_user.id, :shop_id => @shop.id), method: :post do %>
                  <button class="btn" style="background-color: #ACD1FB;"> 
                    <div>
                      <span style="color: white;"> 关注 </span>
                    </div>
                  </button>
                <% end %>
              <% else %>
                <% @current_followshop = Followship.find_by(user_id: current_user.id, shop_id: @shop.id) %>
                <%= link_to @current_followshop, method: :delete do %>
                  <button class="btn" style="background-color: #F6CADC;"> 
                    <div>
                      <span style="color: white;"> 取消关注 </span>
                    </div>
                  </button>
                <% end %>
              <% end %>
            <% elsif current_user.role == 2 %>
              <button class="btn" style="background-color: #ACD1FB;"> 
                <div>
                  <span style="color: white;"> 关注 </span>
                </div>
              </button>
            <% elsif current_user.role == 3 %>
              <button class="btn" style="background-color: #ACD1FB;"> 
                <div>
                  <span style="color: white;"> 关注 </span>
                </div>
              </button>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path, method: :get do %>
              <button class="btn" style="background-color: #ACD1FB;"> 
                <div>
                  <span style="color: white;"> 关注 </span>
                </div>
              </button>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="d-flex flex-column" style="margin-left: 3%; width: 77%; background-color: #F5F5F5; border-radius: 20px;">
    <!-- right display part -->
    <div class="m-4">
      <!-- Nav pills -->
      <div class="ms-3 mt-2">
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link active" data-bs-toggle="pill" href="#home">主页</a>
          </li>
          <li class="nav-item ms-3">
            <a class="nav-link" data-bs-toggle="pill" href="#menu1">所有商品</a>
          </li>
        </ul>
      </div>

      <!-- Tab panes -->
      <div class="tab-content">
        <div class="tab-pane ms-3 mt-3 fade show active" id="home">
          <!-- topsales products && latest products -->
          <div class="mb-4" style="margin-top: 35px;">
            <h3> 热销榜 </h3>
          </div>

          <% @shop_products = Product.where(user_id: @shop.user_id) %>
          <% @ranked_products = (@shop_products.sort_by &:sales).reverse.first(10) %>
          <div class="d-flex flex-column mt-2">
            <% count = 1 %>
            <% @ranked_products.each do |ranked_product| %>
              <div class="d-flex mb-4">
                <div class="me-3 mt-1">
                  <div class="d-flex justify-content-center" style="background-color: #B8D0EB; border-radius: 10px; width: 20px;">
                    <span><%= count %></span>
                  </div>
                  <% count = count + 1 %>
                </div>

                <div>
                  <%= link_to ranked_product, method: :get do %>
                    <img src="<%= (url_for(ranked_product.image_dir)) %>" style="height: 8rem; width: 8rem; border-radius: 20px;" alt="...">
                  <% end %>
                </div>

                <div class="ms-3 my-2 d-flex flex-column">
                  <div>
                    <%= link_to ranked_product, style: "text-decoration: none; color: black;", method: :get do %>
                      <h5 style="font-size: 20px;"> <%= ranked_product.name%> </h5>
                    <% end %>
                  </div>

                  <div>
                    <%= link_to ranked_product, style: "text-decoration: none; color: black;", method: :get do %>
                      <span> <%= ranked_product.description %> </span>
                    <% end %>
                  </div>

                  <div class="mt-1">
                    <%= link_to ranked_product, style: "text-decoration: none; color: black;", method: :get do %>
                      <span>¥ <%= ranked_product.price.to_f %> </span>
                    <% end %>
                  </div>

                  <div class="mt-1">
                    <%= link_to ranked_product, style: "text-decoration: none; color: black;", method: :get do %>
                      <span style="font-size: 14px;">已售出:  <%= ranked_product.sales %></span>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>

          <div class="mt-4 mb-4">
            <h3> 新上架商品 </h3>
          </div>

          <% @latest_products = (@shop_products.sort_by &:created_at).reverse.first(10) %>
          
          <div class="d-flex flex-column mt-2">
            <% count = 1 %>
            <% @latest_products.each do |latest_product| %>
              <div class="d-flex mb-4">
                <div class="me-3 mt-1">
                  <div class="d-flex justify-content-center" style="background-color: #B8D0EB; border-radius: 10px; width: 20px;">
                    <span><%= count %></span>
                  </div>
                  <% count = count + 1 %>
                </div>

                <div>
                  <%= link_to latest_product, method: :get do %>
                    <img src="<%= (url_for(latest_product.image_dir)) %>" style="height: 8rem; width: 8rem; border-radius: 20px;" alt="...">
                  <% end %>
                </div>

                <div class="ms-3 my-2 d-flex flex-column">
                  <div>
                    <%= link_to latest_product, style: "text-decoration: none; color: black;", method: :get do %>
                      <h5 style="font-size: 20px;"> <%= latest_product.name%> </h5>
                    <% end %>
                  </div>

                  <div>
                    <%= link_to latest_product, style: "text-decoration: none; color: black;", method: :get do %>
                      <span> <%= latest_product.description %> </span>
                    <% end %>
                  </div>

                  <div class="mt-1">
                    <%= link_to latest_product, style: "text-decoration: none; color: black;", method: :get do %>
                      <span>¥ <%= latest_product.price.to_f %> </span>
                    <% end %>
                  </div>

                  <div class="mt-1 d-flex align-items-center">
                    <%= image_tag 'clock.png', style: 'height:16px; width:16px; margin-right: 8px;' %>
                    <%= link_to latest_product, style: "text-decoration: none; color: black;", method: :get do %> 
                      <span style="font-size: 14px; color: grey;"><%= time_ago_in_words latest_product.created_at %></span>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>

        <div class="tab-pane ms-1 fade" style="margin-top: 35px;" id="menu1">
          <!-- all products -->
          <div class="d-flex flex-wrap" style="margin-top: 30px; margin-left: 10px;">
            <% @shop_products.each do |shop_product| %>
              <div class="d-flex flex-column mb-4" style="margin-right: 30px;">
                <div>
                  <%= link_to shop_product, method: :get do %>
                    <img src="<%= (url_for(shop_product.image_dir)) %>" style="height: 9.5rem; width: 9.5rem; border-radius: 20px;" alt="...">
                  <% end %>
                </div>

                <div class="ms-3 mt-3 d-flex flex-column">
                  <%= link_to shop_product, style: "text-decoration: none; color: black;", method: :get do %>
                    <h5 style="font-size: 20px;"> <%= shop_product.name%> </h5>
                  <% end %>

                  <%= link_to shop_product, style: "text-decoration: none; color: black;", method: :get do %>
                    <span>¥ <%= shop_product.price.to_f %> </span>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>