JShop/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :followships
  resources :shops
  resources :deliveries

  resources :s_orders do
    post :is_shipped, on: :member
    post :is_delivered, on: :member
  end

  resources :orders do
    post :is_completed, on: :member
    post :is_cancelled, on: :member
  end

  resources :favorites

  resources :carts do
    post :inc_one, on: :member
    post :dec_one, on: :member
  end

  resources :products

  devise_for :users
  
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

JShop/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

JShop/app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

JShop/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user
  belongs_to :s_order
end

JShop/app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :s_order
end

JShop/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

JShop/app/models/followship.rb
class Followship < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

JShop/app/models/order.rb
class Order < ApplicationRecord
    has_many :s_orders, dependent: :destroy

    scope :filter_by_status, -> (status) { where status: status }
end

JShop/app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image_dir
    validates :name, :price, :description, :image_dir,  presence: true
    belongs_to :user

    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :carts, dependent: :destroy
    has_many :s_orders, dependent: :destroy
end

JShop/app/models/s_order.rb
class SOrder < ApplicationRecord
  belongs_to :order
  belongs_to :product
  has_one :delivery, dependent: :destroy
  has_one :comment, dependent: :destroy

  scope :filter_by_status, -> (status) { where status: status }
end

JShop/app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
end

JShop/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:login]

  has_many :carts, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one :shop, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :followships, dependent: :destroy

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  attr_writer :login

  validate :validate_username

  def login
    @login || self.username || self.email
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
end

JShop/app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
  before_action :set_delivery, only: %i[ show edit update destroy ]

  # GET /deliveries or /deliveries.json
  def index
    @deliveries = Delivery.all
  end

  # GET /deliveries/1 or /deliveries/1.json
  def show
  end

  # GET /deliveries/new
  def new
    @delivery = Delivery.new
  end

  # GET /deliveries/1/edit
  def edit
  end

  # POST /deliveries or /deliveries.json
  def create
    @delivery = Delivery.new(delivery_params)

    respond_to do |format|
      if @delivery.save
        format.html { redirect_to @delivery, notice: "Delivery was successfully created." }
        format.json { render :show, status: :created, location: @delivery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @delivery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deliveries/1 or /deliveries/1.json
  def update
    respond_to do |format|
      if @delivery.update(delivery_params)
        format.html { redirect_to @delivery, notice: "Delivery was successfully updated." }
        format.json { render :show, status: :ok, location: @delivery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @delivery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deliveries/1 or /deliveries/1.json
  def destroy
    @delivery.destroy
    respond_to do |format|
      format.html { redirect_to deliveries_url, notice: "Delivery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delivery
      @delivery = Delivery.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def delivery_params
      params.require(:delivery).permit(:s_order_id, :postman_name)
    end
end

JShop/app/helpers/application_helper.rb
module ApplicationHelper
end

JShop/app/helpers/carts_helper.rb
module CartsHelper
end

JShop/app/helpers/comments_helper.rb
module CommentsHelper
end

JShop/app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

JShop/app/helpers/favorites_helper.rb
module FavoritesHelper
end

JShop/app/helpers/followships_helper.rb
module FollowshipsHelper
end

JShop/app/helpers/home_helper.rb
module HomeHelper
end

JShop/app/helpers/orders_helper.rb
module OrdersHelper
end

JShop/app/helpers/products_helper.rb
module ProductsHelper
end

JShop/app/helpers/s_orders_helper.rb
module SOrdersHelper
end

JShop/app/helpers/shops_helper.rb
module ShopsHelper
end

JShop/app/views/deliveries/_form.html.erb
<%= form_with(model: delivery) do |form| %>
  <% if delivery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(delivery.errors.count, "error") %> prohibited this delivery from being saved:</h2>

      <ul>
        <% delivery.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :s_order_id %>
    <%= form.text_field :s_order_id %>
  </div>

  <div class="field">
    <%= form.label :postman_name %>
    <%= form.text_field :postman_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

JShop/app/views/deliveries/edit.html.erb
<h1>Editing Delivery</h1>

<%= render 'form', delivery: @delivery %>

<%= link_to 'Show', @delivery %> |
<%= link_to 'Back', deliveries_path %>

JShop/app/views/deliveries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Deliveries</h1>

<table>
  <thead>
    <tr>
      <th>S order</th>
      <th>Postman name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deliveries.each do |delivery| %>
      <tr>
        <td><%= delivery.s_order_id %></td>
        <td><%= delivery.postman_name %></td>
        <td><%= link_to 'Show', delivery %></td>
        <td><%= link_to 'Edit', edit_delivery_path(delivery) %></td>
        <td><%= link_to 'Destroy', delivery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Delivery', new_delivery_path %>

JShop/app/views/deliveries/new.html.erb
<h1>New Delivery</h1>

<%= render 'form', delivery: @delivery %>

<%= link_to 'Back', deliveries_path %>

JShop/app/views/deliveries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>S order:</strong>
  <%= @delivery.s_order_id %>
</p>

<p>
  <strong>Postman name:</strong>
  <%= @delivery.postman_name %>
</p>

<%= link_to 'Edit', edit_delivery_path(@delivery) %> |
<%= link_to 'Back', deliveries_path %>